/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package front;

/**
 *
 * @author admin
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        usuario = new java.awt.TextField();
        senha = new javax.swing.JPasswordField();
        Entrar = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        Usuario = new java.awt.Label();
        label1 = new java.awt.Label();
        planoDeFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(usuario);
        usuario.setBounds(220, 480, 160, 20);

        senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaActionPerformed(evt);
            }
        });
        getContentPane().add(senha);
        senha.setBounds(220, 510, 160, 20);

        Entrar.setBackground(new java.awt.Color(153, 153, 153));
        Entrar.setText("Entrar");
        Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarActionPerformed(evt);
            }
        });
        getContentPane().add(Entrar);
        Entrar.setBounds(150, 550, 80, 30);

        sair.setBackground(new java.awt.Color(153, 153, 153));
        sair.setText("Sair");
        getContentPane().add(sair);
        sair.setBounds(270, 550, 90, 30);

        Usuario.setBackground(new java.awt.Color(204, 204, 204));
        Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Usuario.setName("Usuario"); // NOI18N
        Usuario.setText("Usuario");
        getContentPane().add(Usuario);
        Usuario.setBounds(140, 480, 80, 20);

        label1.setBackground(new java.awt.Color(204, 204, 204));
        label1.setText("Senha");
        getContentPane().add(label1);
        label1.setBounds(140, 510, 80, 20);

        planoDeFundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\image projeto\\vientam.jpg")); // NOI18N
        planoDeFundo.setText("jLabel1");
        getContentPane().add(planoDeFundo);
        planoDeFundo.setBounds(-20, -370, 570, 1200);

        setBounds(0, 0, 565, 672);
    }// </editor-fold>//GEN-END:initComponents

    private void senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaActionPerformed

    private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed
        telaPrincipal tela = new telaPrincipal();
        tela.setVisible(true);
    }//GEN-LAST:event_EntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Entrar;
    private java.awt.Label Usuario;
    private javax.swing.JFrame jFrame1;
    private java.awt.Label label1;
    private javax.swing.JLabel planoDeFundo;
    private javax.swing.JButton sair;
    private javax.swing.JPasswordField senha;
    private java.awt.TextField usuario;
    // End of variables declaration//GEN-END:variables
}
